var vcbl = {
    'rus': {
        name_mask: 'Загрузка...',
        title_alert_error: 'Ошибка',
        data_transfer_failed: 'Передача данных не состоялась, попробуйте ещё раз',
        login_win_button: 'Вход',
        login_win_title: 'Авторизация',
        blank_text: 'Поле обязательно для заполнения',
        basis_title: 'Базисы',
        trader_title: 'Трейдеры',
        new_trader_title: 'Новый трейдер',
        refresh_title: 'Обновить',
        add_trader_title: 'Добавить трейдера',
        save_button_title: 'Сохранить',
        title_grid_values: 'Значения',
        title_alert_warning: 'Предупреждение',
        difference_between_changes: 'Разница между изменениями минимальной и максимальной ценами более 10%!',
        change_minimum_price: 'Изменение минимальной цены более чем на 25% от предыдущего значения!',
        change_maximum_price: 'Изменение максимальной цены более чем на 25% от предыдущего значения!',
        title_column_country: 'Страна',
        title_column_basis: 'Базис',
        title_column_condition: 'Условие',
        title_column_trader: 'Трейдер',
        title_column_currency: 'Валюта',
        title_column_date: 'Дата',
        title_column_date_new: 'Дата new',
        title_del_new_data: 'Удаление новых данных',
        data_deletion_failed: 'Удаление данных не состоялось, попробуйте ещё раз',
        title_column_comment_rus: 'Комментарий (rus)',
        title_column_comment_eng: 'Комментарий (eng)',
        only_actual_records: 'Только актуальные записи',
        until_end_data_entry: 'до окончания занесения данных осталось',
        until_start_data_entry: 'до начала занесения данных осталось',
        add_value: 'Добавить значение',
        select_basis: 'Выберите базис',
        select_product: 'Выберите продукт',
        select_terms: 'Выберите условие',
        select_currency: 'Выберите валюту',
        select_trader: 'Выберите трейдера'
    },
    'eng': {
        name_mask: 'Loading...',
        title_alert_error: 'Error',
        data_transfer_failed: 'Data transfer failed, please try again',
        login_win_button: 'Login',
        login_win_title: 'Authorization',
        blank_text: 'Required field',
        basis_title: 'Basis',
        trader_title: 'Traders',
        new_trader_title: 'New trader',
        refresh_title: 'Refresh',
        add_trader_title: 'Add a trader',
        save_button_title: 'Save',
        title_grid_values: 'Values',
        title_alert_warning: 'Warning',
        difference_between_changes: 'The difference between changes in the minimum and maximum prices is more than 10%!',
        change_minimum_price: 'Change in the minimum price by more than 25% from the previous value!',
        change_maximum_price: 'Change in the maximum price by more than 25% from the previous value!',
        title_column_country: 'Country',
        title_column_basis: 'Basis',
        title_column_condition: 'Condition',
        title_column_trader: 'Trader',
        title_column_currency: 'Currency',
        title_column_date: 'Date',
        title_column_date_new: 'Date new',
        title_del_new_data: 'Deleting new data',
        data_deletion_failed: 'Data deletion failed, please try again',
        title_column_comment_rus: 'Comment (rus)',
        title_column_comment_eng: 'Comment (eng)',
        only_actual_records: 'Only up-to-date entries',
        until_end_data_entry: 'until the end of the data entry',
        until_start_data_entry: 'until the start of data entry',
        add_value: 'Add value',
        select_basis: 'Select basis',
        select_product: 'Select product',
        select_terms: 'Select terms',
        select_currency: 'Select currency',
        select_trader: 'Select trader'
    }
};